@startuml

skinparam defaultFontSize 10.5

interface IBaseController {

}

abstract class ABaseController {

}

class ResponseFactory {
	{static} Response<T> createResponse()
	{static} Response<T> success()
	{static} Response<T> error()
}

class Response<T> {
	- int status: 标记是否成功
	- int code: 状态码
	- String msg : 状态码对应的解释
	- T data: 传输的数据
	- Object extra : 用于拓展的字段
}

class CustomerController {
	- customer_service : 基本管理
	- skill_service : 技能值管理
	
	+ Customer login()
	+ Boolean register()
	+ Boolean update_customer()
	+ List get_customer_ranks() : 获取排行榜
}

class ArticleController {
	- article_service : 基本管理
	- favorite_article_service : 收藏夹服务
	- comment_article_service : 评论服务

	+ commit_to_services() : 提交具体服务
}

class ProblemController {
	- problem_service : 基本管理
	- tag_problem_service : 知识点服务
	- favorite_probelm_service : 收藏夹服务
	- submission_service : 提交记录服务
	- error_problems_service : 错题本服务
	- comment_problem_service : 评论服务

	+ commit_to_service() : 提交具体服务
}

IBaseController <|.. ABaseController

ABaseController .right.> ResponseFactory
ResponseFactory .right.> Response

ABaseController <|-- ArticleController
ABaseController <|-- CustomerController
ABaseController <|-- ProblemController

@enduml