@startuml

[配置文件\nConfig.xml] as config
[映射文件\nSqlMapping\nConfig.xml] as sqlMapper

sqlMapper -up-> config
config -right-> [Configuration]
[应用程序] -down-> [Configuration]
[Configuration] -down-> [SqlSessionFactory]
[SqlSessionFactory] -down-> [SqlSession]
[SqlSession] -right-> [MappedStatements]
[SqlSession] -down-> [提交数据库]
@enduml